#variavbles
@baseUrl = http://localhost:3333

# /helth
# @name health
GET {{baseUrl}}/health

###

#Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

#create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "sala teste",
    "description": "sala teste"
}

###
@roomId = {{createRoom.response.body.$.roomId}}
###

#get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

#create question
# @name createQuestion
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
    "question": "qual o teste?",
}